# Generated by Django 5.0.4 on 2024-07-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0004_alter_exercise_name'),
        ('planning', '0002_workoutplan_scheduledworkout_workoutsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='name',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Exercise.exercise'),
        ),
    ]
