# Generated by Django 5.0.3 on 2024-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exercise', '0002_remove_exercise_difficulty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], max_length=50)),
                ('equipment', models.CharField(choices=[('None', 'None'), ('Dumbbells', 'Dumbbells'), ('Barbell', 'Barbell'), ('Machine', 'Machine'), ('Bands', 'Bands'), ('Kettlebells', 'Kettlebells')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('steps', models.TextField()),
            ],
        ),
    ]
