# Generated by Django 5.0.3 on 2024-07-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Squat', 'Squat'), ('Bicep Curl', 'Bicep Curl'), ('Plank', 'Plank'), ('Deadlift', 'Deadlift'), ('Shoulder Press', 'Shoulder Press'), ('Lateral Raise', 'Lateral Raise'), ('Leg Press', 'Leg Press'), ('Tricep Dip', 'Tricep Dip'), ('Kettlebell Swing', 'Kettlebell Swing'), ('Russian Twist', 'Russian Twist'), ('Push-up', 'Push-up'), ('Running', 'Running'), ('Swimming', 'Swimming'), ('Cycling', 'Cycling')], max_length=100),
        ),
    ]
