# Generated by Django 5.0.6 on 2024-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0002_alter_goal_goal_type_alter_goal_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance_improvement', 'Endurance Improvement'), ('flexibility', 'Flexibility')], max_length=50),
        ),
    ]
