# Generated by Django 5.0.4 on 2024-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
